api/urls.py
#encoding:utf-8

from django.urls import path
from .view import v1
app_name = "api"

urlpatterns = [
    path('v1/client/<ip>/',v1.ClinetView.as_view(),name='client'),
    path('v1/client/<ip>/resource/',v1.ResourceView.as_view(),name='resource'),

]

cmdb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('asset/', include('asset.urls')),
    path('webanalysis/', include('webanalysis.urls')),
    path('api/', include('api.urls')),
]

user/urls.py
from django.urls import path
from user import views

app_name = 'user'

urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.login, name="login"),
    path('valid_login/', views.valid_login, name="valid_login"),
    path('logout/', views.logout, name="logout"),
    path('delete/', views.delete, name="delete"),
    path('view/', views.view, name="view"),
    path('update/', views.update, name="update"),
    path('insert_view/', views.insert_view, name="insert_view"),
    path('insert/', views.insert, name="insert"),
    path('find_view/', views.find_view, name="find_view"),
    path('find/', views.find, name="find"),
    path('passwd_view/', views.passwd_view, name="passwd_view"),
    path('passwd/', views.passwd, name="passwd"),
    path('nginx_log/', views.nginx_log, name="nginx_log"),
    path('insert/ajax', views.insert_ajax, name="insert_ajax"),
    path('delete/ajax', views.delete_ajax, name="delete_ajax"),
    path('view/ajax', views.view_ajax, name="view_ajax"),
    path('update/ajax', views.update_ajax, name="update_ajax"),
]

webanalysis/urls.py
from django.urls import path
from webanalysis import views

app_name = 'webanalysis'

urlpatterns = [
    path('index/', views.index, name="index"),
    path('upload/', views.upload, name="upload"),
    path('dist_status_code/', views.dist_status_code, name="dist_status_code"),
    path('trend_visit/', views.trend_visit, name="trend_visit"),
    path('devops/user/', views.devops_user, name="devops_user"),
]

user/models.py
#encoding:utf-8

from django.db import models
from .dbuntils import MysqlConnect
import hashlib

def encrypt_password(password):
    if not isinstance(password,bytes):
        password = str(password).encode()
    md5 = hashlib.md5()
    md5.update(password)
    return md5.hexdigest()


class User(models.Model):
    name = models.CharField(max_length=32, null=False, default='') # name varchar(32) not null defalut=''
    password = models.CharField(max_length=512,null=False, default='')
    age = models.IntegerField(null=False,default=0)
    sex = models.BooleanField(null=False,default=True)
    tel = models.CharField(max_length=32,null=False,default='')
    create_time = models.DateTimeField(null=False)
    addr = models.CharField(max_length=32,null=False,default='')


    @classmethod
    def delete_user(cls,uid):
        return cls.objects.filter(id=uid).delete()


    def as_dict(self):  # 这没有id=None,name=''...，只是说明没有默认值，没有说参数传不进来
        return {'id':self.id, 'name':self.name, 'age':self.age, 'sex':self.sex, 'tel':self.tel}

    @classmethod
    def get_nginx_log(cls):
        cnt, result = MysqlConnect.excute_sql(
            'select ip,time,url,status,count(*) from nginx_log group by ip,time,url,status order by count(*) desc limit 10')
        return cnt, result

webanalysis/models.py
from django.db import models
from django.db import connection

class AccessLogFile(models.Model):
    name = models.CharField(max_length=128,null=False,default='')
    path = models.CharField(max_length=1024,null=False,default='')
    created_time = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(default=0)

class Accesslog(models.Model):
    file_id = models.IntegerField(default=0)
    ip = models.GenericIPAddressField(null=0,default='0.0.0.0')
    url = models.CharField(max_length=1024,null=False,default='')
    status_code = models.IntegerField(default=0,null=False)
    access_time = models.DateTimeField(null=False)

    @classmethod
    def dist_status_code(cls,file_id):
        cursor = connection.cursor()    #直接创建连接，获取游标
        cursor.execute("select status_code,count(*) from webanalysis_accesslog where file_id=%s group by status_code",(file_id))
        rt = cursor.fetchall()
        legend = []
        series = []
        for line in rt:
            legend.append(str(line[0]))
            # series.append({"name":line[0],"value":line[1]})    #line[0]为status_code，line[1]为count(*)，即次数
            series.append({"name":str(line[0]),"value":line[1]})    #line[0]为status_code，line[1]为count(*)，即次数
        return legend, series
    @classmethod
    def trend_visit(cls,file_id):
        cursor = connection.cursor()
        cursor.execute("select date_format(access_time, '%%Y-%%m-%%d %%H:00:00') as day, count(*) from webanalysis_accesslog where file_id=%s and access_time >= %s group by day;",(file_id,"1900.01.01"))
        rt = cursor.fetchall()
        xAxis = []
        series = []
        for line in rt:
            xAxis.append(line[0])
            series.append(line[1])

        return xAxis,series

user/views.py
#encoding: utf-8
from django.shortcuts import render,redirect
from django.http import HttpResponse, JsonResponse


from .models import User,encrypt_password
from .validators import User_Valid
import time

def index(request):
    if not request.session.get('user'):
        return redirect('/user/login/')
    return render(request, 'user/index.html', {
        'users':User.objects.all()
    })

def login(request):
    return render(request, 'user/login.html')

def valid_login(request):
    name = request.POST.get('name')
    password = request.POST.get('password')
    password = encrypt_password(password)
    print(password)
    user = User_Valid.vaction_login(name,password)
    if user:
        request.session['user'] =user.as_dict()
        return redirect('/user/index/')
    else:
        return render(request, 'user/login.html',{
            'name':name,
            'errors':{'defalut':'用户名或密码错误'}
        })

def logout(request):
    request.session.flush()
    return redirect('/user/login/')

def delete(request):
    if not request.session.get('user'):
        return redirect('/user/login/')
    uid = request.GET.get('uid','')
    User.delete_user(uid)
    return redirect('/user/index/')

def delete_ajax(request):
    if not request.session.get('user'):
        return JsonResponse({'code': 403})
    uid = request.GET.get('uid','')
    User.delete_user(uid)
    return JsonResponse({'code': 200})



def view(request):
    if not request.session.get('user'):
        return redirect('/user/login/')
    uid = request.GET.get('uid', '')
    return render(request,'user/view.html',{
        'user':User.objects.get(pk=uid)
    })

def view_ajax(request):
    if not request.session.get('user'):
        return JsonResponse({'code': 403})
    uid = request.GET.get('uid', '')
    # user = User.objects.get(pk=uid)
    # return JsonResponse({'user':User.objects.get(pk=uid)})  # 返回的结果User object (17)，不是Json格式
    return JsonResponse({'id':User.objects.get(pk=uid).id,'name':User.objects.get(pk=uid).name,'age':User.objects.get(pk=uid).age,'tel':User.objects.get(pk=uid).tel,'tel':User.objects.get(pk=uid).tel,'sex':User.objects.get(pk=uid).sex})  # 返回的结果User object (17)，不是Json格式

    # return render(request,'user/view.html',{
    #     'user':User.objects.get(pk=uid)
    # })

def update(request):
    if not request.session.get('user'):
        return redirect('/user/login/')
    is_valid , user, errors = User_Valid.valid_update_user(request.POST)
    if is_valid:
        user.save()  # user是一个对象，可以通过user.name、user.age获取name和age所以可以创建一个实例的函数通过self.name去获取name
        return redirect('/user/index/')
    else:
        return render(request, 'user/view.html',{
           'user':user,
            'errors':errors
        })

def update_ajax(request):
    if not request.session.get('user'):
        return JsonResponse({'code': 403})
    # print(request.POST.get('tel'))
    is_valid , user, errors = User_Valid.valid_update_user(request.POST)
    print(is_valid)
    if is_valid:
        user.save()  # user是一个对象，可以通过user.name、user.age获取name和age所以可以创建一个实例的函数通过self.name去获取name
        return JsonResponse({'code': 200})
    else:
        return JsonResponse({'code': 400, 'error': errors})


def insert_view(request):
    if not request.session.get('user'):
        return redirect('/user/login/')
    return render(request,'user/insert_view.html')

def insert(request):
    if not request.session.get('user'):
        return redirect('/user/login/')
    is_valid, user, errors = User_Valid.valid_insert_user(request.POST)
    user.password = encrypt_password(user.password) #md5密码
    if is_valid:
        user.save()
        return redirect('/user/index/')
    else:
        return render(request, 'user/insert_view.html',{
           'user':user,
            'errors':errors
        })

def insert_ajax(request):
    if not request.session.get('user'):
        return JsonResponse({'code':403})
    print(request.POST)
    is_valid, user, errors = User_Valid.valid_insert_user(request.POST)
    user.password = encrypt_password(user.password)
    if is_valid:
        user.save()
        return JsonResponse({'code': 200})
    else:
        return JsonResponse({'code':400,'error':errors})



def find_view(request): #这个函数主要是添加一个新的页面
    if not request.session.get('user'):
        return redirect('/user/login/')
    return render(request,'user/find_view.html')

def find(request):
    if not request.session.get('user'):
        return redirect('/user/login/')
    is_valid, user, errors = User_Valid.valid_find_user(request.POST)
    if is_valid:
        # finduser = user.find_user()
        return render(request, 'user/find_user_list.html', {
            'user':User.objects.get(id=user.id)
        })
    else:
        return render(request, 'user/find_view.html',{
            'user':user,
            'errors':errors
        } )

def passwd_view(request):
    if not request.session.get('user'):
        return redirect('/user/login/')
    return render(request, 'user/passwd_view.html', {
        'user':request.session['user']
    })

def passwd(request):
    if not request.session.get('user'):
        return redirect('/user/login/')

    is_valid, user, errors  = User_Valid.valid_passwd_user(request.POST,request.session.get('user')['id'])
    user.password = encrypt_password(user.password)
    if is_valid:
        # user.update_password(request.session.get('user')['id'])
        user.save()
        return redirect('/user/index/')
    else:
        return render(request, 'user/passwd_view.html', {
            'user':user,
            'errors':errors
        })

def nginx_log(request):
    cnt, result = User.get_nginx_log()
    return render(request,'user/nginx_log_view.html',{
            'results':result #这里是一个元组，元组里面有多个元组
    })

webanalysis/views.py
import os
import json
import time
from functools import wraps

from django.conf import settings
from django.shortcuts import render,redirect
from django.http import HttpResponse,JsonResponse
from webanalysis.models import AccessLogFile,Accesslog
from django.contrib.auth.models import User
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger

def login_required(func):   #定义一个装饰器，无需添加url，添加@即可调用

    @wraps(func)
    def wrapper(request,*args,**kwargs):
        if request.session.get('user') is None:
            if request.is_ajax():
                return JsonResponse({'code':403,'result':[]})
            return redirect('user:login')

        return func(request, *args,**kwargs)

    return wrapper

@login_required #装饰器，无需添加url，直接调用login_required
def index(request):
    files = AccessLogFile.objects.filter(status=0).order_by('-created_time')[:10]
    return render(request,'webanalysis/index.html',{'files':files})

def upload(request):
    log = request.FILES.get('log')
    # print('name:',log.name,"size:",log.size,"type:",log.content_type)
    if log:
        path = os.path.join(settings.BASE_DIR,'media','uploads',str(time.time()))
        fhandler = open(path,"wb")

        for chunk in log.chunks():
            fhandler.write(chunk)
        fhandler.close()

        obj = AccessLogFile(name=log.name,path=path)
        obj.save()
        path = os.path.join(settings.BASE_DIR,'media','notices',str(time.time()))   #主要用于找路径和id对应关系
        with open(path,'w') as fhandler:
            fhandler.write(json.dumps({'id':obj.id,'path':obj.path}))

    return HttpResponse("上传成功")


@login_required
def dist_status_code(request):
    legend, series = Accesslog.dist_status_code(request.GET.get('id', 0))
    return JsonResponse({'code':200, 'result': {'legend':legend,'series':series}})


@login_required
def trend_visit(request):
    xAxis, series = Accesslog.trend_visit(request.GET.get('id',0))
    print(xAxis,series)
    return JsonResponse({"code":200, "result":{"xAxis":xAxis, "series":series}})


def devops_user(request):
    users = User.objects.filter()
    paginator = Paginator(users,10)
    page = request.GET.get('page')
    try:
        users_page = paginator.page(page)
    except PageNotAnInteger:
        users_page = paginator.page(1)
    except EmptyPage:
        users_page = paginator.page(paginator.num_pages)
    return render(request,"webanalysis/user.html",{"users_page":users_page})

webanalysis/templates/webanalysis/index.html
{% extends "base.html" %}
{% block title %}日志分析{%endblock%}
{% block nax_webanalysis %}active{% endblock%}
{% block jumbotron %}
<div class="row">
    <div class="col-md-6">
        <form class="form-inline">
            <div class="form-group">
                <label class="form-label sr-only">文件选择</label>
                <select class="form-control" id="accesslog_file">
                    {% for item in files %}
                    <option value="{{ item.id }}">{{ item.path }}</option>
                    {% endfor %}
                </select>
            </div>
        </form>
    </div>
    <div class="col-md-6">
        <form class="form-inline" method="POST" enctype="multipart/form-data" action="{% url "webanalysis:upload" %}">
            {% csrf_token %}
            <div class="form-group">
                <label class="form-label sr-only">上传文件</label>
                <input type="file" name="log"/>
            </div>
            <input type="submit" class="btn btn-default" value="上传文件" />
        </form>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div id="dist_status_code" style="width:100%;height:400px">1</div>
    </div>
    <div class="col-md-6">
        <div id="trend_visit" style="width:100%;height:400px">2</div>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div id="dist_geo" style="width:100%;height:600px">3</div>
    </div>
</div>
{% endblock %}


{% block js %}
    var chart_dist_status_code = echarts.init(document.getElementById('dist_status_code'));
    var chart_trend_visit = echarts.init(document.getElementById('trend_visit'));
    var chart_dist_geo = echarts.init(document.getElementById('dist_geo'));

{#    var option_dist_status_code = {#}
{#    title : {#}
{#        text: '状态码分布',#}
{#        subtext: '',#}
{#        x:'center'#}
{#    },#}
{#    tooltip : {#}
{#        trigger: 'item',#}
{#        formatter: "{a} <br/>{b} : {c} ({d}%)"#}
{#    },#}
{#    legend: {#}
{#        orient: 'vertical',#}
{#        x: 'left',#}
{#        data: []#}
{#    },#}
{#    series : [#}
{#        {#}
{#            name: '状态码分布',#}
{#            type: 'pie',#}
{#            radius : '55%',#}
{#            center: ['50%', '60%'],#}
{#            data:[],#}
{#            itemStyle: {#}
{#                emphasis: {#}
{#                    shadowBlur: 10,#}
{#                    shadowOffsetX: 0,#}
{#                    shadowColor: 'rgba(0, 0, 0, 0.5)'#}
{#                }#}
{#            }#}
{#        }#}
{#    ]#}
{#};#}


var option_dist_status_code = {
    title : {
        text: '状态码分布',
        subtext: '',
        x:'center'
    },
    tooltip : {
        trigger: 'item',
        formatter: "{a} <br/>{b} : {c} ({d}%)"
    },
    legend: {
        orient : 'vertical',
        x : 'left',
        data:[]
    },
    toolbox: {
        show : true,
        orient: 'vertical',
        x: 'right',
        y: 'center',
        feature : {
            mark : {show: true},
            dataView : {show: true, readOnly: false},
            magicType : {
                show: true,
                type: ['pie', 'funnel'],
                option: {
                    funnel: {
                        x: '25%',
                        width: '50%',
                        funnelAlign: 'left',
                        max: 1548
                    }
                }
            },
            restore : {show: true},
            saveAsImage : {show: true}
        }
    },
    calculable : true,
    series : [
        {
            name:'状态码分布',
            type:'pie',
            radius : '55%',
            center: ['50%', '60%'],
            data:[]
        }
    ]
};




var option_trend_visit = {
    title : {
    text: '每小时访问量',
    subtext: '',
    x:'center'
    },

    tooltip : {
        trigger: 'axis',
        axisPointer : {            // 坐标轴指示器，坐标轴触发有效
            type : 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
        }
    },
    legend: {
         x:'left',
        data:['直接访问']
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis : [
        {
            type : 'category',
            data : []
        }
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
        {
            name:'直接访问',
            type:'bar',
            data:[]
        },

    ]
};


function reload() {
    var id = jQuery('#accesslog_file').val();  <!-- 获取id为access对应的value的值-->
    reload_dist_status_code(id);    <!--下面调用-->
    reload_trend_visit(id)
}

function reload_dist_status_code(id) {
    jQuery.get("{% url  'webanalysis:dist_status_code' %}",{'id':id}, function(result) {
        if(result.code == 200) {
            chart_dist_status_code.clear();
            option_dist_status_code['legend']['data'] = result.result.legend;
            option_dist_status_code.series[0].data = result.result.series;
            // 使用刚指定的配置项和数据显示图表。
            chart_dist_status_code.setOption(option_dist_status_code);
        }
    },'json')
}

function reload_trend_visit(id) {
    jQuery.get("{% url 'webanalysis:trend_visit' %}",{"id":id},function(result) {
        if(result.code == 200) {
            chart_trend_visit.clear();
            option_trend_visit['xAxis'][0]['data'] = result.result.xAxis
            option_trend_visit['series'][0]['data'] = result.result.series
            chart_trend_visit.setOption(option_trend_visit)
            console.log(typeof(result.result.xAxis))
            console.log(typeof(result.result.series))
        }
    },'json')
}

reload();

jQuery('#accesslog_file').on('change',function() {
    reload();
});

{% endblock %}


webanalysis/templates/webanalysis/user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户列表</title>
</head>
<body>
    <table border="1">
        <thead>
            <tr>
                <th>ID</th>
                <th>用户名</th>
                <th>邮箱</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users_page %}
                <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.username }}</td>
                <td>{{ user.email }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% if users_page.has_previous %}
        <a href="?page={{ users_page.previous_page_number }}">上一页</a>
    {% endif %}
    {% for pg in users_page.paginator.page_range %}
        {% if pg == users_page.number %}
            <a href="?page={{ pg }}">{{ pg }}</a>
        {% else %}
            <a href="?page={{ pg }}">{{ pg }}</a>
        {% endif %}
    {% endfor %}
    {% if users_page.has_next %}
        <a href="?page={{ users_page.next_page_number }}">下一页</a>
    {% endif %}
</body>
</html>