api/urls.py
#encoding:utf-8

from django.urls import path
from .view import v1
app_name = "api"

urlpatterns = [
    path('v1/client/<ip>/',v1.ClinetView.as_view(),name='client'),
    path('v1/client/<ip>/resource/',v1.ResourceView.as_view(),name='resource'),

]

cmdb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('asset/', include('asset.urls')),
    path('webanalysis/', include('webanalysis.urls')),
    path('api/', include('api.urls')),
]

user/urls.py
from django.urls import path
from user import views

app_name = 'user'

urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.login, name="login"),
    path('valid_login/', views.valid_login, name="valid_login"),
    path('logout/', views.logout, name="logout"),
    path('delete/', views.delete, name="delete"),
    path('view/', views.view, name="view"),
    path('update/', views.update, name="update"),
    path('insert_view/', views.insert_view, name="insert_view"),
    path('insert/', views.insert, name="insert"),
    path('find_view/', views.find_view, name="find_view"),
    path('find/', views.find, name="find"),
    path('passwd_view/', views.passwd_view, name="passwd_view"),
    path('passwd/', views.passwd, name="passwd"),
    path('nginx_log/', views.nginx_log, name="nginx_log"),
    path('insert/ajax', views.insert_ajax, name="insert_ajax"),
    path('delete/ajax', views.delete_ajax, name="delete_ajax"),
    path('view/ajax', views.view_ajax, name="view_ajax"),
    path('update/ajax', views.update_ajax, name="update_ajax"),
]

user/models.py
#encoding:utf-8

from django.db import models
from .dbuntils import MysqlConnect
import hashlib

def encrypt_password(password):
    if not isinstance(password,bytes):
        password = str(password).encode()
    md5 = hashlib.md5()
    md5.update(password)
    return md5.hexdigest()


class User(models.Model):
    name = models.CharField(max_length=32, null=False, default='') # name varchar(32) not null defalut=''
    password = models.CharField(max_length=512,null=False, default='')
    age = models.IntegerField(null=False,default=0)
    sex = models.BooleanField(null=False,default=True)
    tel = models.CharField(max_length=32,null=False,default='')
    create_time = models.DateTimeField(null=False)
    addr = models.CharField(max_length=32,null=False,default='')


    @classmethod
    def delete_user(cls,uid):
        return cls.objects.filter(id=uid).delete()


    def as_dict(self):  # 这没有id=None,name=''...，只是说明没有默认值，没有说参数传不进来
        return {'id':self.id, 'name':self.name, 'age':self.age, 'sex':self.sex, 'tel':self.tel}

    @classmethod
    def get_nginx_log(cls):
        cnt, result = MysqlConnect.excute_sql(
            'select ip,time,url,status,count(*) from nginx_log group by ip,time,url,status order by count(*) desc limit 10')
        return cnt, result

user/views.py
#encoding: utf-8
from django.shortcuts import render,redirect
from django.http import HttpResponse, JsonResponse


from .models import User,encrypt_password
from .validators import User_Valid
import time

def index(request):
    if not request.session.get('user'):
        return redirect('/user/login/')
    return render(request, 'user/index.html', {
        'users':User.objects.all()
    })

def login(request):
    return render(request, 'user/login.html')

def valid_login(request):
    name = request.POST.get('name')
    password = request.POST.get('password')
    password = encrypt_password(password)
    print(password)
    user = User_Valid.vaction_login(name,password)
    if user:
        request.session['user'] =user.as_dict()
        return redirect('/user/index/')
    else:
        return render(request, 'user/login.html',{
            'name':name,
            'errors':{'defalut':'用户名或密码错误'}
        })

def logout(request):
    request.session.flush()
    return redirect('/user/login/')

def delete(request):
    if not request.session.get('user'):
        return redirect('/user/login/')
    uid = request.GET.get('uid','')
    User.delete_user(uid)
    return redirect('/user/index/')

def delete_ajax(request):
    if not request.session.get('user'):
        return JsonResponse({'code': 403})
    uid = request.GET.get('uid','')
    User.delete_user(uid)
    return JsonResponse({'code': 200})



def view(request):
    if not request.session.get('user'):
        return redirect('/user/login/')
    uid = request.GET.get('uid', '')
    return render(request,'user/view.html',{
        'user':User.objects.get(pk=uid)
    })

def view_ajax(request):
    if not request.session.get('user'):
        return JsonResponse({'code': 403})
    uid = request.GET.get('uid', '')
    # user = User.objects.get(pk=uid)
    # return JsonResponse({'user':User.objects.get(pk=uid)})  # 返回的结果User object (17)，不是Json格式
    return JsonResponse({'id':User.objects.get(pk=uid).id,'name':User.objects.get(pk=uid).name,'age':User.objects.get(pk=uid).age,'tel':User.objects.get(pk=uid).tel,'tel':User.objects.get(pk=uid).tel,'sex':User.objects.get(pk=uid).sex})  # 返回的结果User object (17)，不是Json格式

    # return render(request,'user/view.html',{
    #     'user':User.objects.get(pk=uid)
    # })

def update(request):
    if not request.session.get('user'):
        return redirect('/user/login/')
    is_valid , user, errors = User_Valid.valid_update_user(request.POST)
    if is_valid:
        user.save()  # user是一个对象，可以通过user.name、user.age获取name和age所以可以创建一个实例的函数通过self.name去获取name
        return redirect('/user/index/')
    else:
        return render(request, 'user/view.html',{
           'user':user,
            'errors':errors
        })

def update_ajax(request):
    if not request.session.get('user'):
        return JsonResponse({'code': 403})
    # print(request.POST.get('tel'))
    is_valid , user, errors = User_Valid.valid_update_user(request.POST)
    print(is_valid)
    if is_valid:
        user.save()  # user是一个对象，可以通过user.name、user.age获取name和age所以可以创建一个实例的函数通过self.name去获取name
        return JsonResponse({'code': 200})
    else:
        return JsonResponse({'code': 400, 'error': errors})


def insert_view(request):
    if not request.session.get('user'):
        return redirect('/user/login/')
    return render(request,'user/insert_view.html')

def insert(request):
    if not request.session.get('user'):
        return redirect('/user/login/')
    is_valid, user, errors = User_Valid.valid_insert_user(request.POST)
    user.password = encrypt_password(user.password) #md5密码
    if is_valid:
        user.save()
        return redirect('/user/index/')
    else:
        return render(request, 'user/insert_view.html',{
           'user':user,
            'errors':errors
        })

def insert_ajax(request):
    if not request.session.get('user'):
        return JsonResponse({'code':403})
    print(request.POST)
    is_valid, user, errors = User_Valid.valid_insert_user(request.POST)
    user.password = encrypt_password(user.password)
    if is_valid:
        user.save()
        return JsonResponse({'code': 200})
    else:
        return JsonResponse({'code':400,'error':errors})



def find_view(request): #这个函数主要是添加一个新的页面
    if not request.session.get('user'):
        return redirect('/user/login/')
    return render(request,'user/find_view.html')

def find(request):
    if not request.session.get('user'):
        return redirect('/user/login/')
    is_valid, user, errors = User_Valid.valid_find_user(request.POST)
    if is_valid:
        # finduser = user.find_user()
        return render(request, 'user/find_user_list.html', {
            'user':User.objects.get(id=user.id)
        })
    else:
        return render(request, 'user/find_view.html',{
            'user':user,
            'errors':errors
        } )

def passwd_view(request):
    if not request.session.get('user'):
        return redirect('/user/login/')
    return render(request, 'user/passwd_view.html', {
        'user':request.session['user']
    })

def passwd(request):
    if not request.session.get('user'):
        return redirect('/user/login/')

    is_valid, user, errors  = User_Valid.valid_passwd_user(request.POST,request.session.get('user')['id'])
    user.password = encrypt_password(user.password)
    if is_valid:
        # user.update_password(request.session.get('user')['id'])
        user.save()
        return redirect('/user/index/')
    else:
        return render(request, 'user/passwd_view.html', {
            'user':user,
            'errors':errors
        })

def nginx_log(request):
    cnt, result = User.get_nginx_log()
    return render(request,'user/nginx_log_view.html',{
            'results':result #这里是一个元组，元组里面有多个元组
    })

user/templates/user/find_user_list.html
{% load static%}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>CMDB后台管理系统</title>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{%  static 'user/login.css'%}">
</head>
<body>
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <table class="table table-striped table-bordered table-hover table-condensed">
                <thead>
                    <tr>
                        <th>用户名</th>
                        <th>年龄</th>
                        <th>性别</th>
                        <th>联系方式</th>
                    </tr>
                </thead>
                <tbody>
                        <tr>
                            <td>{{ user.name }}</td>
                            <td>{{ user.age }}</td>
                            <!--<td>{{ user.sex }}</td>-->
                            <td>
                                {% if user.sex == 0 %}
                                    女
                                {% else %}
                                    男
                                {% endif %}
                            </td>
                            <td>{{ user.tel }}</td>
                        </tr>
                </tbody>
            </table>
        <a class="btn btn-primary" href="{% url 'user:index' %}">返回</a>
        </div>
    </div>
</body>
</html>

user/templates/user/find_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CMDB后台管理系统</title>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{%  static 'user/login.css'%}">
</head>
<body>
    <div class="row">
        <div class="container">
            <form class="form-signin" action="{% url 'user:find' %}" method="POST">
                <h2 class="form-signin-heading">用户查找</h2>
                {% if errors %}
                    {%for key, error in errors.items %}
                        <div class="alert alert-danger" role="alert">{{ error }}</div>
                        <!--{{ error }}<br/>-->
                    {%endfor%}
                {%endif%}
                {% csrf_token %}
                <label for="name" class="sr-only">用户名</label>
                <input class="form-control" type="text" name="name" />
                <!--<input type="submit" value="查找"/>-->
                <button class="btn btn-lg btn-primary btn-block" type="submit">查找</button>
            </form>
        </div>
    </div>
</body>
</html>

user/templates/user/insert_view.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CMDB后台管理系统</title>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}">
</head>
<body>
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <form action="{% url 'user:insert' %}" method="POST">
                {% if errors %}
                    {%for key, error in errors.items %}
                        {{ error }}<br/>
                    {%endfor%}
                {%endif%}
                {% csrf_token %}

                <div class="form-group">
                    <div class="col-md-2">
                        <label>用户名</label>
                    </div>
                    <div class="col-md-10">
                        <input class="form-control" type="text" name="name" value="{{ user.name }}"/>
                    </div>
                </div>


            <div class="form-group">
                    <div class="col-md-2">
                        <label>密码</label>
                    </div>
                    <div class="col-md-10">
                        <input class="form-control" type="password" name="password" />
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-2">
                        <label>年龄</label>
                    </div>
                    <div class="col-md-10">
                        <input class="form-control" type="text" name="age" value="{{ user.age }}"/>
                    </div>
                </div>

                <div  class="form-group">
                    <div class="col-md-3">
                        <label class="radio-inline">性别</label>
                    </div>

                    <div class="col-md-9">
                    <label class="radio-inline">
                        <input type="radio" name="sex" value="1" {% if user.sex != 0 %} checked {% endif %} />男
                    </label>
                    <label class="radio-inline">
                        <input type="radio" name="sex" value="0" {% if user.sex == 0 %} checked {% endif %} />女
                    </label>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-2">
                        <label>电话</label>
                    </div>
                    <div class="col-md-10">
                        <input class="form-control" type="text" name="tel" value="{{ user.tel }}"/>
                    </div>
                </div>

                <!--<input type="submit" value="增加"/>-->
                <button class="btn btn-success btn-xs" type="submit">增加</button>


            </form>
        </div>
    </div>
</body>
</html>

user/templates/user/login.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <title>CMDB登陆</title>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{%  static 'user/login.css'%}">
  </head>

  <body>
    <div class="container">
      <form class="form-signin" action="{% url 'user:valid_login' %}" method="POST">
        <h2 class="form-signin-heading">CMDB后台管理系统</h2>
            {% if errors %}
                {%for key, error in errors.items %}
                    <div class="alert alert-danger" role="alert">{{ error }}</div>
                    <!--{{ error }}-->
                {%endfor%}
            {%endif%}
            {% csrf_token %}
        <label for="name" class="sr-only">用户名</label>
        <input type="text" id="name" class="form-control" placeholder="用户名" name="name" value="{{ name }}">
        <label for="password" class="sr-only">密码</label>
        <input type="password" id="password" class="form-control" placeholder="密码" name="password">
        <!--<div class="checkbox">-->
          <!--<label>-->
            <!--<input type="checkbox" value="remember-me"> Remember me-->
          <!--</label>-->
        <!--</div>-->
        <button class="btn btn-lg btn-primary btn-block" type="submit">登陆</button>

      </form>
    </div>
          <!--<button class="btn btn-lg btn-primary btn-block" type="submit">提示</button>-->
    <!--<script type="text/javascript" src="{% static 'test.js' %}"></script>-->
    <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
  <script type="text/javascript">
      var sum = 0

      for(var i =0;i <=100;i++ ) {
          sum += i
      }
      console.log(sum)
  </script>
  </body>
</html>

user/templates/user/nginx_log_view.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>nginx日志</title>
</head>
<body>
<table border="1">
    <thead>
        <tr>
            <th>IP</th>
            <th>TIME</th>
            <th>URL</th>
            <th>STATUS</th>
            <th>COUNT</th>
        </tr>
    </thead>
    <tbody>
        {% for result in results %}
            <tr>
                <td>{{ result.0 }}</td>
                <td>{{ result.1 }}</td>
                <td>{{ result.2 }}</td>
                <td>{{ result.3 }}</td>
                <td>{{ result.4 }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
</body>
</html>

user/templates/user/passwd_view.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CMDB后台管理系统</title>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}">
</head>
<body>
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <form action="{% url 'user:passwd' %}" method="POST">
                {% if errors %}
                    {%for key, error in errors.items %}
                        <div class="alert alert-danger" role="alert">{{ error }}</div>
                        <!--{{ error }}<br/>-->
                    {%endfor%}
                {%endif%}
                {% csrf_token %}
                <input type="hidden" name="id" value="{{ user.id }}" />

                <div class="form-group">
                    <div class="col-md-3">
                        <label>用户名</label>
                    </div>
                    <div class="col-md-9">
                        <input class="form-control" type="text" name="name" value="{{ user.name }}"/>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-3">
                        <label>旧密码</label>
                    </div>
                    <div class="col-md-9">
                        <input class="form-control" type="password" name="old_passwd" />
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-3">
                        <label>新密码</label>
                    </div>
                    <div class="col-md-9">
                        <input class="form-control" type="password" name="new_passwd_one" />
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-3">
                        <label>确认密码</label>
                    </div>
                    <div class="col-md-9">
                        <input class="form-control" type="password" name="new_passwd_two" />
                    </div>
                </div>
                <!--<button class="btn btn-lg btn-primary btn-block" type="submit">查找</button>-->

                <div class="form-group">
                    <div class="col-md-12">
                        <button class="btn btn-lg btn-success btn-xs" type="submit">确认修改</button>
                    </div>
                    <!--<div class="col-md-9">-->

                    <!--</div>-->
                </div>
                <!--<input type="submit" value="增加"/>-->


            </form>
        </div>
    </div>
</body>

user/templates/user/view.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CMDB后台管理系统</title>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}">
</head>

<body>
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <form action="{% url 'user:update' %}" method="POST">
                {% if errors %}
                    {%for key, error in errors.items %}
                        <div class="alert alert-danger" role="alert">{{ error }}</div>
                        <!--{{ error }}<br/>-->
                    {%endfor%}
                {%endif%}
                {% csrf_token %}
                <input type="hidden" name="id" value="{{ user.id }}" />
                <div class="form-group">
                    <div class="col-md-2">
                        <label>用户名</label>
                    </div>
                    <div class="col-md-10">
                        <input class="form-control" type="text" name="name" value="{{ user.name }}"/>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-2">
                        <label>年龄</label>
                    </div>
                    <div class="col-md-10">
                        <input class="form-control" type="text" name="age" value="{{ user.age }}"/>
                    </div>
                </div>

                <div  class="form-group">
                    <div class="col-md-3">
                        <label class="radio-inline">性别</label>
                    </div>

                    <div class="col-md-9">
                    <label class="radio-inline">
                        <input type="radio" name="sex" value="1" {% if user.sex != 0 %} checked {% endif %} />男
                    </label>
                    <label class="radio-inline">
                        <input type="radio" name="sex" value="0" {% if user.sex == 0 %} checked {% endif %} />女
                    </label>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-2">
                        <label>电话</label>
                    </div>
                    <div class="col-md-10">
                        <input class="form-control" type="text" name="tel" value="{{ user.tel }}"/>
                    </div>
                </div>

                <!--<div class="form-group">-->
                    <!--<div class="col-md-2">-->
                        <!--<label></label>-->
                    <!--</div>-->
                    <!--<div class="col-md-10">-->
                    <!--<input class="btn btn-primary btn-block" type="submit" value="修改"/>-->
                    <!--</div>-->
               <!--</div>-->
                <button class="btn btn-success btn-xs" type="submit">修改</button>
        </form>
        </div>
    </div>
</body>