api/urls.py
#encoding:utf-8

from django.urls import path
from .view import v1
app_name = "api"

urlpatterns = [
    path('v1/client/<ip>/',v1.ClinetView.as_view(),name='client'),
    path('v1/client/<ip>/resource/',v1.ResourceView.as_view(),name='resource'),

]

asset/urls.py
from django.urls import path
from asset import views

app_name = 'asset'
urlpatterns = [
    path('', views.index, name="index"),
    path('list/ajax', views.list_ajax, name="list_ajax"),
    path('view/ajax', views.view_ajax, name="view_ajax"),
    path('update/ajax', views.update_ajax, name="update_ajax"),
    path('delete/ajax', views.delete_ajax, name="delete_ajax"),
    path('resource/ajax', views.resource_ajax, name="resource_ajax"),
]

cmdb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('asset/', include('asset.urls')),
    path('webanalysis/', include('webanalysis.urls')),
    path('api/', include('api.urls')),
]

user/urls.py
from django.urls import path
from user import views

app_name = 'user'

urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.login, name="login"),
    path('valid_login/', views.valid_login, name="valid_login"),
    path('logout/', views.logout, name="logout"),
    path('delete/', views.delete, name="delete"),
    path('view/', views.view, name="view"),
    path('update/', views.update, name="update"),
    path('insert_view/', views.insert_view, name="insert_view"),
    path('insert/', views.insert, name="insert"),
    path('find_view/', views.find_view, name="find_view"),
    path('find/', views.find, name="find"),
    path('passwd_view/', views.passwd_view, name="passwd_view"),
    path('passwd/', views.passwd, name="passwd"),
    path('nginx_log/', views.nginx_log, name="nginx_log"),
    path('insert/ajax', views.insert_ajax, name="insert_ajax"),
    path('delete/ajax', views.delete_ajax, name="delete_ajax"),
    path('view/ajax', views.view_ajax, name="view_ajax"),
    path('update/ajax', views.update_ajax, name="update_ajax"),
]

webanalysis/urls.py
from django.urls import path
from webanalysis import views

app_name = 'webanalysis'

urlpatterns = [
    path('index/', views.index, name="index"),
    path('upload/', views.upload, name="upload"),
    path('dist_status_code/', views.dist_status_code, name="dist_status_code"),
    path('trend_visit/', views.trend_visit, name="trend_visit"),
    path('devops/user/', views.devops_user, name="devops_user"),
]

templates/base.html
{% load static%}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{%endblock%} </title>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{%  static 'user/navbar.css'%}">
    <link rel="stylesheet" type="text/css" href="{%  static 'DataTables-1.10.15/media/css/jquery.dataTables.min.css'%}">
    <link rel="stylesheet" type="text/css" href="{%  static 'DataTables-1.10.15/media/css/dataTables.bootstrap.min.css'%}">
    <link rel="stylesheet" type="text/css" href="{%  static 'sweetalert-1.0.1/dist/sweetalert.css'%}">
  </head>

  <body>
    <div class="container-fluid">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">CMDB后台管理系统</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="{% block nav_user %}{% endblock%}"><a href="{% url 'user:index' %}">用户管理</a></li>
              <li class="{% block nav_asset %}{% endblock%}"><a href="{% url 'asset:index' %}">资产管理</a></li>
              <li class="{% block nav_webanalysis %}{% endblock%}"><a href="{% url 'webanalysis:index' %}">日志分析</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class="active"><a href="./">当前用户：{{request.session.user.name}} <span class="sr-only">(current)</span></a></li>
              <li><a href="{% url 'user:passwd_view' %}">修改当前密码</a></li>
              <li><a href="{% url 'user:logout' %}">退出登录</a></li>
            </ul>

          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

      <div class="jumbotron">
            {% block jumbotron %}{% endblock %}
      </div>
    </div>
        {% block dialogs %}{%endblock%}
    
    <script type="text/javascript" src="{% static 'jquery/jquery-1.12.4.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'DataTables-1.10.15/media/js/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'sweetalert-1.0.1/dist/sweetalert.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'echarts-2.2.7/build/dist/echarts-all.js' %}"></script>
    {% block scritps %}{% endblock %}
    <script type="text/javascript">

            // 参考http://www.datatables.club/
            $(document).ready(function() {
                {% block js %}{% endblock %}
            });
    </script>
  </body>
</html>